---
- name: Ping Servers
  hosts: all
  vars:
    key1: true
    key2: "value2"
  gather_facts: no
  tasks:
    - name: Ping
      ping:

    - name: Print variables
      when: ansible_distribution is defined
      debug:
        msg: "OS = {{ ansible_distribution }}"